import Link from 'next/link';

export const dynamic = 'force-dynamic';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-ivory-200 px-4 py-12 dark:bg-charcoal-900">
      <article className="mx-auto max-w-2xl space-y-6 text-stone-700 dark:text-stone-300">
        <Link href="/" className="text-sm text-bordeaux-400 hover:text-bordeaux-600 transition-colors dark:text-bordeaux-300">
          &larr; Back to app
        </Link>

        <h1 className="heading-serif text-3xl text-bordeaux-600 dark:text-ivory-200">Privacy Policy</h1>
        <p className="text-sm text-stone-500">Last updated: February 2026</p>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">What we collect</h2>
          <p>WineJourney collects the minimum data needed to provide you with a personalized wine experience:</p>
          <ul className="list-disc space-y-1 ps-6">
            <li>Your email address (for authentication)</li>
            <li>Display name (optional, for personalization)</li>
            <li>Wine taste preferences (from the onboarding quiz and wines you like)</li>
            <li>Your cellar and wishlist data</li>
            <li>Wine search queries and uploaded images (processed by OpenAI for identification)</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">How we use your data</h2>
          <ul className="list-disc space-y-1 ps-6">
            <li>To authenticate you and maintain your session</li>
            <li>To generate personalized wine recommendations</li>
            <li>To store your cellar, wishlist, and taste profile</li>
            <li>Wine images and search queries are sent to OpenAI for processing and are subject to <a href="https://openai.com/policies/privacy-policy" className="text-bordeaux-400 underline" target="_blank" rel="noopener noreferrer">OpenAI&apos;s Privacy Policy</a></li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">AI-generated content</h2>
          <p>Wine information displayed in the app — including ratings, tasting notes, taste profiles, serving suggestions, and food pairings — is generated by artificial intelligence (OpenAI). This data represents AI estimates and may not be fully accurate. Ratings shown are approximate estimates and are not sourced directly from any third-party rating provider. We encourage you to verify important details (such as allergens, alcohol content, or pricing) from the wine producer or retailer directly.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Wine images</h2>
          <p>Wine bottle images are sourced from publicly available web sources to help you identify wines. These images remain the property of their respective owners. If you are a rights holder and wish to have an image removed, please contact us and we will promptly remove it.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Data storage</h2>
          <p>Your data is stored securely on Supabase (PostgreSQL) with row-level security enabled. Each user can only access their own data.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Third-party services</h2>
          <ul className="list-disc space-y-1 ps-6">
            <li><strong>Supabase</strong> — authentication and database</li>
            <li><strong>OpenAI</strong> — wine identification, recommendations, and AI-generated content</li>
            <li><strong>Vercel</strong> — hosting and analytics</li>
            <li><strong>Google</strong> — OAuth sign-in (optional)</li>
            <li><strong>Vivino</strong> — external links for wine verification (we link to Vivino search pages so you can verify wine details; we do not collect data from Vivino)</li>
            <li><strong>Wine-Searcher</strong> — external links to find wine prices and stores</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Your rights</h2>
          <p>You can request deletion of your account and all associated data at any time by contacting us. You can also export your cellar and wishlist data from the app.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Content removal</h2>
          <p>If you believe any content in the app infringes your intellectual property rights, please contact us with details and we will investigate and remove the content promptly.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Contact</h2>
          <p>For privacy-related questions or content removal requests, please reach out via the app settings page or email us at <a href="mailto:asaffz@winejourney.co" className="text-bordeaux-400 underline">asaffz@winejourney.co</a>.</p>
        </section>
      </article>
    </div>
  );
}
