import Link from 'next/link';

export const dynamic = 'force-dynamic';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-ivory-200 px-4 py-12 dark:bg-charcoal-900">
      <article className="mx-auto max-w-2xl space-y-6 text-stone-700 dark:text-stone-300">
        <Link href="/" className="text-sm text-bordeaux-400 hover:text-bordeaux-600 transition-colors dark:text-bordeaux-300">
          &larr; Back to app
        </Link>

        <h1 className="heading-serif text-3xl text-bordeaux-600 dark:text-ivory-200">Privacy Policy</h1>
        <p className="text-sm text-stone-500">Last updated: March 2026</p>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">What we collect</h2>
          <p>WineJourney collects the minimum data needed to provide you with a personalized wine experience:</p>
          <ul className="list-disc space-y-1 ps-6">
            <li>Your email address (for authentication)</li>
            <li>Display name, country, birthday, and gender (optional, for personalization)</li>
            <li>Wine taste preferences (from the onboarding quiz and wines you like)</li>
            <li>Your cellar, wishlist, and consumed-wines data</li>
            <li>Wine search queries and uploaded images (processed by OpenAI for identification)</li>
            <li>Sommelier conversation history (your chats with Pier, the AI sommelier)</li>
            <li>Push notification subscription data (endpoint and encryption keys, if you enable notifications)</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">How we use your data</h2>
          <ul className="list-disc space-y-1 ps-6">
            <li>To authenticate you and maintain your session</li>
            <li>To generate personalized wine recommendations</li>
            <li>To store your cellar, wishlist, and taste profile</li>
            <li>Wine images and search queries are sent to OpenAI for processing and are subject to <a href="https://openai.com/policies/privacy-policy" className="text-bordeaux-400 underline" target="_blank" rel="noopener noreferrer">OpenAI&apos;s Privacy Policy</a></li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">AI-generated content</h2>
          <p>Wine information displayed in the app — including ratings, tasting notes, taste profiles, serving suggestions, and food pairings — is generated by artificial intelligence (OpenAI). This data represents AI estimates and may not be fully accurate. Ratings shown are approximate estimates and are not sourced directly from any third-party rating provider. We encourage you to verify important details (such as allergens, alcohol content, or pricing) from the wine producer or retailer directly.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Wine images</h2>
          <p>Wine bottle images are sourced from publicly available web sources to help you identify wines. These images remain the property of their respective owners. If you are a rights holder and wish to have an image removed, please contact us and we will promptly remove it.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Data storage</h2>
          <p>Your data is stored securely on Supabase (PostgreSQL) with row-level security enabled. Each user can only access their own data.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Third-party services</h2>
          <ul className="list-disc space-y-1 ps-6">
            <li><strong>Supabase</strong> — authentication and database</li>
            <li><strong>OpenAI</strong> — wine identification, recommendations, and AI-generated content</li>
            <li><strong>Vercel</strong> — hosting, analytics, and performance monitoring</li>
            <li><strong>Google</strong> — OAuth sign-in (optional)</li>
            <li><strong>Sentry</strong> — error tracking and diagnostics (no personal data is sent; PII is stripped before transmission)</li>
            <li><strong>Upstash</strong> — rate limiting infrastructure (processes IP-based rate limit keys only)</li>
            <li><strong>Serper</strong> — image search API used to find wine bottle images from publicly available web sources</li>
            <li><strong>Resend</strong> — transactional email delivery for admin notifications</li>
            <li><strong>Vivino</strong> — external links for wine verification (we link to Vivino search pages so you can verify wine details; we do not collect data from Vivino)</li>
            <li><strong>Wine-Searcher</strong> — external links to find wine prices and stores</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Data retention</h2>
          <p>Your account data (profile, cellar, wishlist, taste profiles, and conversation history) is retained as long as your account is active. When you delete your account via the Settings page, all associated data is permanently removed from our systems. Temporary data such as PKCE authentication verifiers is automatically purged after 15 minutes. Wine match cache entries may persist for up to 30 days.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Data processing location</h2>
          <p>Your data is processed and stored using cloud infrastructure provided by Supabase (AWS), Vercel, and OpenAI. These services may process data in multiple regions, including the United States and the European Union. By using WineJourney, you consent to the transfer and processing of your data in these locations.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Your rights</h2>
          <p>Depending on your jurisdiction, you may have rights under data protection laws such as the GDPR (EU) or CCPA (California). These may include the right to access, correct, delete, or export your personal data, and the right to object to or restrict certain processing.</p>
          <p>You can exercise many of these rights directly within the app:</p>
          <ul className="list-disc space-y-1 ps-6">
            <li><strong>Delete your account</strong> and all associated data from the Settings page</li>
            <li><strong>Export your data</strong> as a JSON file from Settings</li>
            <li><strong>Update your personal information</strong> from Settings</li>
          </ul>
          <p>For any additional data-related requests, contact us at <a href="mailto:asaffz@winejourney.co" className="text-bordeaux-400 underline">asaffz@winejourney.co</a>.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Children&apos;s privacy</h2>
          <p>WineJourney is intended for users of legal drinking age in their jurisdiction. We do not knowingly collect personal data from anyone under the legal drinking age. If you believe we have collected data from a minor, please contact us and we will promptly delete it.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Cookies and analytics</h2>
          <p>WineJourney uses essential cookies for authentication and language preferences. We also use Vercel Analytics for anonymous usage statistics and Sentry for error tracking. You can manage your cookie preferences from the cookie consent banner shown on your first visit.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Content removal</h2>
          <p>If you believe any content in the app infringes your intellectual property rights, please contact us with details and we will investigate and remove the content promptly.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Contact</h2>
          <p>For privacy-related questions or content removal requests, please reach out via the app settings page or email us at <a href="mailto:asaffz@winejourney.co" className="text-bordeaux-400 underline">asaffz@winejourney.co</a>.</p>
        </section>
      </article>
    </div>
  );
}
