import Link from 'next/link';

export const dynamic = 'force-dynamic';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-ivory-200 px-4 py-12 dark:bg-charcoal-900">
      <article className="mx-auto max-w-2xl space-y-6 text-stone-700 dark:text-stone-300">
        <Link href="/" className="text-sm text-bordeaux-400 hover:text-bordeaux-600 transition-colors dark:text-bordeaux-300">
          &larr; Back to app
        </Link>

        <h1 className="heading-serif text-3xl text-bordeaux-600 dark:text-ivory-200">Terms of Service</h1>
        <p className="text-sm text-stone-500">Last updated: March 2026</p>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Acceptance of Terms</h2>
          <p>By using WineJourney, you agree to these Terms of Service and our Privacy Policy. If you do not agree, please do not use the app.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Description of Service</h2>
          <p>WineJourney is a wine discovery and collection management tool. The app uses AI to identify wines, generate taste profiles, and provide personalized recommendations. Wine information, ratings, and recommendations are generated by AI and should be treated as suggestions, not professional advice.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Age Requirement</h2>
          <p>You must be of legal drinking age in your jurisdiction to use WineJourney. By creating an account, you confirm that you meet this requirement. We reserve the right to terminate accounts if we reasonably believe this requirement is not met.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">User Accounts</h2>
          <ul className="list-disc space-y-1 ps-6">
            <li>You are responsible for maintaining the security of your account</li>
            <li>You must provide accurate information when creating an account</li>
            <li>You may not use the service for any illegal purpose</li>
            <li>We reserve the right to suspend accounts that violate these terms</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">AI-Generated Content</h2>
          <p>Wine information displayed in the app — including ratings, tasting notes, taste spectrum profiles, match scores, serving suggestions, and food pairings — is generated by artificial intelligence (OpenAI). While we strive for accuracy, this content may contain errors or inaccuracies.</p>
          <ul className="list-disc space-y-1 ps-6">
            <li><strong>Ratings</strong> shown are AI-estimated approximations and are not sourced directly from any third-party rating provider. They are intended as a general guide only.</li>
            <li><strong>Match scores</strong> and taste comparisons are AI-generated based on your preferences and may vary between sessions.</li>
            <li><strong>Tasting notes and descriptions</strong> are AI-generated and may not reflect the actual wine accurately.</li>
          </ul>
          <p>Always verify important information (such as allergens, alcohol content, or pricing) from the wine producer or retailer directly.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Third-Party Content and Links</h2>
          <p>The app may contain links to third-party websites (such as Vivino and Wine-Searcher) for wine verification and purchasing. We are not responsible for the content, accuracy, or availability of these external sites. Wine images displayed in the app are sourced from publicly available web sources and remain the property of their respective owners.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Intellectual Property</h2>
          <p>Wine names, winery names, and related trademarks belong to their respective owners. WineJourney does not claim ownership of any third-party wine brands or imagery. If you believe any content infringes your intellectual property rights, please contact us at <a href="mailto:asaffz@winejourney.co" className="text-bordeaux-400 underline">asaffz@winejourney.co</a> and we will promptly investigate and remove the content.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Limitation of Liability</h2>
          <p>WineJourney is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to inaccurate wine information, AI-generated recommendations, or reliance on estimated ratings.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Your Data</h2>
          <p>You retain ownership of the data you provide to WineJourney. You can export your cellar, wishlist, and taste profile data at any time from the Settings page. You can also delete your account and all associated data permanently. For details on how we handle your data, see our <a href="/privacy" className="text-bordeaux-400 underline">Privacy Policy</a>.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Termination</h2>
          <p>We may suspend or terminate your access to WineJourney at any time, with or without notice, if we believe you have violated these terms or if we discontinue the service. You may also delete your account at any time from the Settings page. Upon termination, your right to use the service ceases immediately.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Indemnification</h2>
          <p>You agree to indemnify and hold harmless WineJourney and its operators from any claims, damages, or expenses arising from your use of the service, your violation of these terms, or your violation of any third-party rights.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Governing Law</h2>
          <p>These terms are governed by the laws of the State of Israel. Any disputes arising from these terms or your use of WineJourney shall be resolved in the competent courts of Tel Aviv-Jaffa, Israel.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Dispute Resolution</h2>
          <p>Before initiating any formal legal proceedings, you agree to contact us at <a href="mailto:asaffz@winejourney.co" className="text-bordeaux-400 underline">asaffz@winejourney.co</a> and attempt to resolve the dispute informally within 30 days.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Changes to Terms</h2>
          <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the updated terms.</p>
        </section>
      </article>
    </div>
  );
}
