import Link from 'next/link';

export const dynamic = 'force-dynamic';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-ivory-200 px-4 py-12 dark:bg-charcoal-900">
      <article className="mx-auto max-w-2xl space-y-6 text-stone-700 dark:text-stone-300">
        <Link href="/" className="text-sm text-bordeaux-400 hover:text-bordeaux-600 transition-colors dark:text-bordeaux-300">
          &larr; Back to app
        </Link>

        <h1 className="heading-serif text-3xl text-bordeaux-600 dark:text-ivory-200">Terms of Service</h1>
        <p className="text-sm text-stone-500">Last updated: February 2026</p>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Acceptance of Terms</h2>
          <p>By using WineJourney, you agree to these Terms of Service and our Privacy Policy. If you do not agree, please do not use the app.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Description of Service</h2>
          <p>WineJourney is a wine discovery and collection management tool. The app uses AI to identify wines, generate taste profiles, and provide personalized recommendations. Wine information, ratings, and recommendations are generated by AI and should be treated as suggestions, not professional advice.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">User Accounts</h2>
          <ul className="list-disc space-y-1 ps-6">
            <li>You are responsible for maintaining the security of your account</li>
            <li>You must provide accurate information when creating an account</li>
            <li>You may not use the service for any illegal purpose</li>
            <li>We reserve the right to suspend accounts that violate these terms</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">AI-Generated Content</h2>
          <p>Wine information, ratings, tasting notes, and recommendations are generated by artificial intelligence (OpenAI). While we strive for accuracy, this content may contain errors. Always verify important information (such as allergens or alcohol content) from the wine producer directly.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Limitation of Liability</h2>
          <p>WineJourney is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to inaccurate wine information or recommendations.</p>
        </section>

        <section className="space-y-3">
          <h2 className="heading-serif text-xl text-bordeaux-600 dark:text-ivory-200">Changes to Terms</h2>
          <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the updated terms.</p>
        </section>
      </article>
    </div>
  );
}
